force-app/main/default/objects/Candidate__c/Candidate__c.object-meta.xml
<CustomObject>
    <label>Candidate</label>
    <nameField>
        <label>First Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Candidates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Candidate_Test__c/Candidate_Test__c.object-meta.xml
<CustomObject>
    <label>Candidate Test</label>
    <nameField>
        <label>Candidate Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Candidate Tests</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Candidate_Test__c/fields/Candidate__c.field-meta.xml
<CustomField>
    <fullName>Candidate__c</fullName>
    <label>Candidate</label>
    <referenceTo>Candidate__c</referenceTo>
    <relationshipLabel>Candidate Tests</relationshipLabel>
    <relationshipName>Candidate_Tests</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/DZTestPortalController.cls
/**
 * @description       : Controller Is Used to Handel Aura Enabled Method.
 * @author            : D - D
 * @group             :
 * @last modified on  : 12-13-2023
 * @last modified by  : D - D
 * Modifications Log
 * Ver   Date         Author   Modification
 * 1.0   12-11-2023   D - D   Initial Version
 **/
public with sharing class DZTestPortalController {
    @AuraEnabled
    public static Map<String, String> getCandidateDetail(String email, String passcode) {
        try {
            return DZTestPortalHelper.getCandidateDetail(email, passcode);
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }
    @AuraEnabled
    public static String updateCandidate(Candidate__c candidate) {
        try {
            DZTestPortalHelper.updateCandidate(candidate);
            return 'Record Update';
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }

    @AuraEnabled
    public static Candidate_Test__c createCandidateTestRecord(Candidate_Test__c candidateTest) {
        try {
            return DZTestPortalHelper.createCandidateTestRecord(candidateTest);
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }

    @AuraEnabled
    public static void calculateTestResult(String quesAndAnsStr, String candiatetestid) {
        try {
            DZTestPortalHelper.calculateTestResult(quesAndAnsStr, candiatetestid);
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }

    @AuraEnabled
    public static Id savePhotoAsAttachment(Id candidateId, String photoDataUrl) {
        try {
            return DZTestPortalHelper.savePhotoAsAttachment(candidateId, photoDataUrl);
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }
}